openapi: 3.0.0
info:
  title: Cart Service API
  version: 1.0.0
  description: API quản lý giỏ hàng của người dùng
servers:
  - url: http://localhost:3003
paths:
  /api/cart:
    get:
      summary: Lấy giỏ hàng hiện tại của user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Trả về danh sách sản phẩm trong giỏ hàng

    post:
      summary: Thêm sản phẩm vào giỏ hàng
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  example: "abc123"
                quantity:
                  type: integer
                  example: 2
      responses:
        "200":
          description: Thêm vào giỏ hàng thành công
        "400":
          description: Dữ liệu không hợp lệ

    delete:
      summary: Xóa toàn bộ giỏ hàng của user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Đã xóa giỏ hàng
        "401":
          description: Không xác thực

  /api/cart/item:
    put:
      summary: Cập nhật số lượng sản phẩm trong giỏ hàng
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  example: "abc123"
                quantity:
                  type: integer
                  example: 5
      responses:
        "200":
          description: Cập nhật thành công
        "400":
          description: Dữ liệu không hợp lệ
        "404":
          description: Không tìm thấy sản phẩm

    delete:
      summary: Xóa một sản phẩm khỏi giỏ hàng
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  example: "abc123"
      responses:
        "200":
          description: Xóa thành công
        "404":
          description: Không tìm thấy sản phẩm

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT